### ISSUE TITLE
More flexible Reaction Counter

### ISSUE THREAD

**Issue by justemoilouise** [charkour/react-reactions#113]
Similar to the existing `FacebookCounter`, but accepts any reaction emoji. Also supports other props such as:
- importantReacts: if there are A LOT of reactions, only show these in the "summary" counter
- className: to easily style text, spacing, etc
- iconSize: as in the `ReactionBarSelector`
- show only the count of reactions received
- opt-in to show a text of `You and X others`

**Comment by charkour** [comment]
That all sounds great! Would you like to make a PR?

**Comment by justemoilouise** [comment]
@charkour Yes! I'll work on this as soon as I have the time as well. 🤞🏼

**Comment by charkour** [comment]
Closed in #118
