### ISSUE TITLE
You didn't show in custom counter

### ISSUE THREAD

**Issue by gh4m21** [charkour/react-reactions#131]
**Describe the bug**
When I try to add the custom counter and when I like the post. **You** didn't show up. And if 3 people like the post, for example, It shows **and 2 other people**.

**My code:**

` 
                    <ReactionCounter
                      reactions={likeArray(post?.Reactions, reactions)}
                      important={["vens"]}
                      user={"vens"}
                      className="text-md text-primary"
                      showOthersAlways={likeArray(post?.Reactions).length > 0 && post?.Reactions?.UserId === user?.id ? true : false}
                      onClick={() => {
                        console.log("will show pop up of person who liked it");
                      }}
                    />
                </p>`

**Expected behavior**
I expected to see **You, you and 2 other people** 

**Screenshots**

![2022-04-13 (2)](https://user-images.githubusercontent.com/34143540/163243630-efbd4299-5735-4e21-93f9-c5cad204c47f.png)

**Comment by gh4m21** [comment]
**code sandbox:**

<iframe src="https://codesandbox.io/embed/react-reactions-issue-7kberm?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="react-reactions issue"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by charkour** [comment]
Hey @gh4m21,

Thanks for the sandbox. I was able to find the issue. 

The counter component is used to show a count of who liked what and list them out. I updated the data to include "vens", and removed the important prop. The counter can be used with the selector.

Sorry for the confusion. In the future, I hope to improve the documentation and make the components easier to use.

[Here is a sandbox](https://codesandbox.io/s/react-reactions-issue-forked-rxo698?file=/src/data/reactions.js) with your expected behavior. Does this do what you are hoping?

**Comment by gh4m21** [comment]
Wow! Thank you so much for resolving this issue so fast for me. 

Your solution was exactly what I was trying to do.
I didn't know if It takes an additional parameters **by**.

By the way, this package is Helpful. 
I have another question, How can I style the emoji with a custom background like the screenshot below?

**Comment by charkour** [comment]
That is a great question. Right now it is not possible to due with the way the library works. Sorry!

I like your suggestion and can release a new version of the package this weekend. Thanks for the great idea and for your patience!

**Comment by gh4m21** [comment]
Thank you so much. Looking forward to seeing this modification on your next release this weekend.

**Comment by charkour** [comment]
An update to style the ReactionCounterEmoji's was released in v0.8.0! 

Here is an [example](https://codesandbox.io/s/react-reactions-issue-forked-rxo698?file=/src/App.js) that styles the emoji's similar to the picture above.

**Comment by gh4m21** [comment]
> An update to style the ReactionCounterEmoji's was released in v0.8.0! 
> 
> 
> 
> Here is an [example](https://codesandbox.io/s/react-reactions-issue-forked-rxo698?file=/src/App.js) that styles the emoji's similar to the picture above. Does this do what you'd like it to do?

Thank you so so much🔥 You literally save me a lot of headache on the project I am currently working on with this updated.🔥🙌🏾

**Comment by gh4m21** [comment]
> An update to style the ReactionCounterEmoji's was released in v0.8.0! 
> 
> 
> 
> Here is an [example](https://codesandbox.io/s/react-reactions-issue-forked-rxo698?file=/src/App.js) that styles the emoji's similar to the picture above. Does this do what you'd like it to do?

@charkour Sorry to bother you again.
Could you please add the ability to customize the container of the ReactionBarSelector the same way you did for ReactionCounterEmoji's?
I will really appreciate that.

**Comment by charkour** [comment]
Happy to help! Which container do you want to update? Perhaps you could post a picture or a link to the code? Thanks!

**Comment by gh4m21** [comment]
> Happy to help! Which container do you want to update? Perhaps you could post a picture or a link to the code? Thanks!

For example for this sandbox:

https://codesandbox.io/s/issue-react-reactions-with-mobile-touch-e7hpnd

I want to style the selector like the previous picture also.
Be able to change the rounded, background...

**Comment by charkour** [comment]
Yes! That can be done. I'll publish an update tomorrow. Thanks for the suggestion and your patience!

You're welcome to also make a PR if you'd like. I'll plan on making this change tomorrow. Thanks and happy easter.

**Comment by gh4m21** [comment]
Thanks! I am planning to make a pull request and see If I can make some update on this packages. When I have a little more time.
Thanks for your help and Happy easter to you also

**Comment by charkour** [comment]
Okay, I will not make the change and will let you make a pull request. If you have any questions, please let me know. Thanks!

**Comment by charkour** [comment]
Hi @gh4m21, using the style prop with the ReactionBarSelector has been released in [v0.10.0](https://www.npmjs.com/package/@charkour/react-reactions/v/0.10.0). Please let me know if there are any issues. Thanks!

**Comment by gh4m21** [comment]
Hey, @charkour. Thank you for letting me know that. I will update it and use it. I was swamped on the parts of the projects, but this update came to the proper and thank you so much!

**Comment by charkour** [comment]
Happy to help! I hope the projects go well.
