### ISSUE TITLE
Like not working on mobile touch

### ISSUE THREAD

**Issue by gh4m21** [charkour/react-reactions#132]
**Describe the bug**
The reactions components **CustomReaction** work perfectly on desktop, but when I try to click on the icon on mobile, it shows **click** in the console and nothing.

**code**

`
            <Fragment>
              <ReactionBarSelector
                className="bg-secondary"
                iconSize={"28px"}
                reactions={reactions}
                onSelect={(label) => handleReaction(label)}
              />
            </Fragment>`

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Iphone 11 pro max
 - OS: IOS 15.3.1
 - Browser  safari
 - Version last version

**Comment by charkour** [comment]
Thanks for the report. I can look at it tonight.

**Comment by charkour** [comment]
Would you be willing to post a code sandbox with a reproduction of the issue? Thanks!

**Comment by gh4m21** [comment]
> Thanks for the report. I can look at it tonight.

Thank you so much.
I will add a code sandbox

**Comment by gh4m21** [comment]
> 

[https://codesandbox.io/s/issue-react-reactions-with-mobile-touch-e7hpnd](url)

**Comment by charkour** [comment]
Hi @gh4m21, thanks for the sandbox. Here is a video I recorded. When I tap an icon, it will correctly console log. Do you expect the icon to shrink to its original size after clicking? Thanks. 


https://user-images.githubusercontent.com/33156025/163299874-1f68a866-fc28-4141-a48e-45ad6019e777.MOV

**Comment by gh4m21** [comment]
> Hi @gh4m21, thanks for the sandbox. Here is a video I recorded. When I tap an icon, it will correctly console log. Do you expect the icon to shrink to its original size after clicking? Thanks.
> 
>  Upload.from.GitHub.for.iOS.MOV

Thank you so much for helping me.
 I got it now. Finally, using a Tooltip to show the component in the perfect place was not a good idea.
I will try to use popover, a modal something else...

**Comment by charkour** [comment]
Great thanks for the reply. Can I close this issue?

**Comment by gh4m21** [comment]
> Great thanks for the reply. Can I close this issue?

Go ahead.
