### ISSUE TITLE
Error when I import Reaction Counter

### ISSUE THREAD

**Issue by ted-dino** [charkour/react-reactions#136]
**Describe the bug**
i dont know what is causing it but everytime I import Reaction Counter and use it in my component I always get an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/84649871/167565050-22e4f715-5625-4fe5-af19-17887ad32846.png)

**Comment by charkour** [comment]
Hi @ted-dino,

Thanks for using the package and sorry that you are having issues! Would you be able to link a reproduction of the issue?

Looking at the stack trace, it seems to be an issue with the component in the package or with props passed to the component.

**Comment by charkour** [comment]
Hey @ted-dino, do you have a reproduction I can see? I tried to reproduce your error but could not. 

Please re-open this issue if the error persists. Sorry I couldn't be of much help.

**Comment by charkour** [comment]
@ted-dino, I tried fixing the error in [v0.10.1](https://www.npmjs.com/package/@charkour/react-reactions/v/0.10.1). Please let me know if the issue persists. Thank you.
