### ISSUE TITLE
SlackSelector header/top bar category icons are missing

### ISSUE THREAD

**Issue by princesust** [charkour/react-reactions#146]
**Describe the bug**
SlackSelector header/top bar category icons are missing. In SlackCounter added an extra icon.

**To Reproduce**
Please visit this [codesandbox](https://codesandbox.io/s/festive-cdn-jr86j9?file=/src/App.js)

**Expected behavior**
Header category icons should show properly.

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/743248/184437582-7ca5ba1e-ce9d-4069-838e-31815fdb24c6.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: 104.0.5112.79

**Additional context**
I created a [video](https://www.loom.com/share/f148718cde6141f3b0c4c162cedbaa0f) to explain it more clearly.

**Comment by charkour** [comment]
Thanks for the video and code sandbox reprodcution! 

Sorry that you are running into this issue. Let me take a look.

**Comment by charkour** [comment]
Hey @princesust,

Fix the issue, please include the slack fonts inside of the `public/fonts` directory. Here are the fonts: https://github.com/charkour/react-reactions/tree/main/example/public/fonts

Sorry, the readme does not say that. I will update that.

Here is a [codesandbox](https://codesandbox.io/s/smoosh-haze-8rlrqn?file=/src/App.js) with the fonts working.
