### ISSUE TITLE
Make a good documentation on the use of selectors and counters

### ISSUE THREAD

**Issue by the-wrong-guy** [charkour/react-reactions#50]
Hey, I am trying to figure out how to use the counters, specifically the pokemon counter. Can you add a demo asap?

**Comment by charkour** [comment]
Yeah, I can make a small demo shorty.

**Comment by charkour** [comment]
Here is a link to the demo on [stackblitz](https://stackblitz.com/edit/react-ts-ktyoyk?file=index.tsx).

The basic documentation can be found on the [readme](https://github.com/charkour/react-reactions#pokemon-counter). 

Do you have suggestions on how to improve the documentation? I am working on making a demo app that uses all selectors and counters.
