### ISSUE TITLE
When only one person reacts , it shows "You and 0 others"

### ISSUE THREAD

**Issue by the-wrong-guy** [charkour/react-reactions#51]
When only one person reacts, it shows "You and 0 others" but I don't want to show " and 0 others"  if there's one  reaction 
So can you remove it or give options to remove it 
![image](https://user-images.githubusercontent.com/52911853/110212628-503f1a00-7ec2-11eb-80a8-821d6ccdc74c.png)

**Comment by charkour** [comment]
Hey! Thanks for the suggestion. I think making it an option would be great. 

I could add that feature tomorrow, or if you'd like it before then or if you want to make a PR, just let me know!

**Comment by charkour** [comment]
Ran out of time to add this feature today. Sorry

**Comment by charkour** [comment]
Live on [`v0.4.0`](https://www.npmjs.com/package/@charkour/react-reactions/v/0.4.0)
