### ISSUE TITLE
Trouble styling some counters

### ISSUE THREAD

**Issue by the-wrong-guy** [charkour/react-reactions#64]
![IMG_20210315_235127](https://user-images.githubusercontent.com/52911853/111202005-64cd9180-85e9-11eb-86f3-2199e4002bb1.jpg)
Hey, can you make more gap between the emoji and text in the counter?

Also, the emojis get squeezed when div width is limited and the text also doesn't break to the next line and  give space to the emojis  maybe you should give the emoji div and emojis some min-width and min-height
![IMG_20210315_235455](https://user-images.githubusercontent.com/52911853/111202916-71061e80-85ea-11eb-841a-3d2a1b9b0eef.jpg)

**Comment by charkour** [comment]
Hi. Thanks for the issue. 

What part of the emoji is squeezing? Can do provide a demo with the issue? Thanks.

**Comment by charkour** [comment]
Closed due to inactivity. Can't reproduce
